import { config, fields, collection, singleton } from '@keystatic/core';

export default config({
  storage: {
    kind: 'local',
  },
  singletons: {
    siteSettings: singleton({
      label: 'Site Settings',
      path: 'src/content/siteSettings/siteSettings',
      format: { data: 'json' },
      schema: {
        schoolName: fields.text({ label: 'School Name' }),
        shortName: fields.text({ label: 'Short Name' }),
        tagline: fields.text({ label: 'Tagline' }),
        description: fields.text({ label: 'Description', multiline: true }),
        logo: fields.image({ label: 'Logo', directory: 'src/assets/images', publicPath: '/src/assets/images' }),
        favicon: fields.image({ label: 'Favicon', directory: 'public', publicPath: '/' }),
        primaryCtaLabel: fields.text({ label: 'Primary CTA Label' }),
        primaryCtaUrl: fields.url({ label: 'Primary CTA URL' }),
        secondaryCtaLabel: fields.text({ label: 'Secondary CTA Label' }),
        secondaryCtaUrl: fields.url({ label: 'Secondary CTA URL' }),
        whatsappUrl: fields.url({ label: 'WhatsApp URL' }),
        instagramUrl: fields.url({ label: 'Instagram URL' }),
        email: fields.text({ label: 'Email' }),
        mapsUrl: fields.url({ label: 'Maps URL' }),
        address: fields.text({ label: 'Address', multiline: true }),
      },
    }),
  },
  collections: {
    quickLinks: collection({
      label: 'Quick Links',
      slugField: 'title',
      path: 'src/content/quickLinks/*',
      format: { data: 'json' },
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        description: fields.text({ label: 'Description', multiline: true }),
        url: fields.url({ label: 'URL' }),
        icon: fields.select({
          label: 'Icon',
          options: [
            { label: 'Link', value: 'link' },
            { label: 'School', value: 'school' },
            { label: 'Info', value: 'info' },
            { label: 'Download', value: 'download' },
            { label: 'Map Pin', value: 'map-pin' },
            { label: 'Message Circle', value: 'message-circle' },
            { label: 'Instagram', value: 'instagram' },
          ],
          defaultValue: 'link',
        }),
        category: fields.select({
          label: 'Category',
          options: [
            { label: 'SPMB', value: 'spmb' },
            { label: 'Program', value: 'program' },
            { label: 'Information', value: 'information' },
            { label: 'Social', value: 'social' },
            { label: 'Contact', value: 'contact' },
            { label: 'Download', value: 'download' },
          ],
          defaultValue: 'information',
        }),
        badge: fields.text({ label: 'Badge (Optional)' }),
        isActive: fields.checkbox({ label: 'Is Active', defaultValue: true }),
        isFeatured: fields.checkbox({ label: 'Is Featured', defaultValue: false }),
        sortOrder: fields.integer({ label: 'Sort Order', defaultValue: 0 }),
      },
    }),
    announcements: collection({
      label: 'Announcements',
      slugField: 'title',
      path: 'src/content/announcements/*',
      format: { data: 'json' },
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        description: fields.text({ label: 'Description', multiline: true }),
        badge: fields.text({ label: 'Badge' }),
        ctaLabel: fields.text({ label: 'CTA Label' }),
        ctaUrl: fields.url({ label: 'CTA URL' }),
        isActive: fields.checkbox({ label: 'Is Active', defaultValue: true }),
        startDate: fields.date({ label: 'Start Date' }),
        endDate: fields.date({ label: 'End Date' }),
      },
    }),
    programs: collection({
      label: 'Programs',
      slugField: 'title',
      path: 'src/content/programs/*',
      format: { data: 'json' },
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        level: fields.select({
          label: 'Level',
          options: [
            { label: 'Preschool', value: 'preschool' },
            { label: 'Elementary', value: 'elementary' },
          ],
          defaultValue: 'preschool',
        }),
        description: fields.text({ label: 'Description', multiline: true }),
        ctaLabel: fields.text({ label: 'CTA Label' }),
        ctaUrl: fields.url({ label: 'CTA URL' }),
        sortOrder: fields.integer({ label: 'Sort Order', defaultValue: 0 }),
        isActive: fields.checkbox({ label: 'Is Active', defaultValue: true }),
      },
    }),
    updates: collection({
      label: 'Updates',
      slugField: 'title',
      path: 'src/content/updates/*',
      schema: {
        title: fields.slug({ name: { label: 'Title' } }),
        excerpt: fields.text({ label: 'Excerpt', multiline: true }),
        category: fields.select({
          label: 'Category',
          options: [
            { label: 'News', value: 'news' },
            { label: 'Parenting', value: 'parenting' },
            { label: 'SPMB', value: 'spmb' },
            { label: 'Activity', value: 'activity' },
            { label: 'Article', value: 'article' },
          ],
          defaultValue: 'news',
        }),
        publishedDate: fields.date({ label: 'Published Date' }),
        isPublished: fields.checkbox({ label: 'Is Published', defaultValue: false }),
        coverImage: fields.image({ label: 'Cover Image', directory: 'src/assets/images/updates', publicPath: '/src/assets/images/updates' }),
        content: fields.markdoc({ label: 'Content' }),
      },
    }),
  },
});
